version: "3"
services:
  xotomicro-front-event-service:
    env_file:
      - token.env
    build:
      context: ./
      dockerfile: docker/dockerfile.development
    #   environment:
    #     - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: xotomicro-front-event-service
    ports:
      - 7071:7071
    volumes:
      - ./:/app
