apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-front-event-service
  name: xotomicro-front-event-service
spec:
  ports:
    - name: "7071"
      port: 7071
      targetPort: 80
  selector:
    io.kompose.service: xotomicro-front-event-service
status:
  loadBalancer: {}
